---
title: "Artisan Roofing and Guttering"
baseURL: "http://www.artisanroofingandguttering.com"
relativeURLs: true
theme: "artisan"
languageCode: "en-us"
metaDataFormat: "yaml"
markup:
  goldmark:
    renderer:
      unsafe: true
...
